Repository softeng2223-inf-uniba/progetto2223-nygaard, pull requests merged in 2023-05, with the labels that each got.

#40 Creata base del codice
  src/main/java/it/uniba/app/App.java
  src/main/java/it/uniba/nygaard/game/Util.java
Labels: code

#43 Revisionato file guida dello studente
  docs/Guida per lo studente.md
  docs/img/ExecuteDockerImage_1.png
  docs/img/ExecuteDockerImage_2.png
  docs/img/manageAccess.png
  docs/img/packageSettings.png
Labels: documentation

#45 Patchata configurazione checkstyle
  config/checkstyle/checkstyle.xml
Labels: patch

#48 Applicata patch CheckStyle 2
  config/checkstyle/checkstyle.xml
Labels: patch

#46 Come giocatore voglio impostare il livello di gioco per variare il numero massimo di tentativi sbagliati
  src/main/java/it/uniba/app/App.java
  src/main/java/it/uniba/nygaard/game/Match.java
  src/main/java/it/uniba/nygaard/game/Util.java
Labels: user story

#50 Come giocatore voglio mostrare il livello di gioco e il numero massimo di tentativi falliti
  src/main/java/it/uniba/app/App.java
  src/main/java/it/uniba/nygaard/game/Match.java
Labels: user story
